Repository team-aliens/dms-front-admin, pull requests merged in 2022-10, with the labels that each got.

#5 (#4) merge: 1차 스프린트에서 사용하는 api관련 기능 추가
  .eslintrc.json
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/jsLinters/eslint.xml
  .idea/prettier.xml
  .prettierrc
  package-lock.json
  package.json
  src/apis/.gitkeep
  src/apis/auth/index.ts
  src/apis/auth/request.ts
  src/apis/auth/response.ts
  src/apis/axios.ts
  src/apis/managers/index.ts
  src/apis/managers/request.ts
  src/apis/managers/response.ts
  src/apis/schools/index.ts
  src/apis/schools/request.ts
  src/apis/schools/response.ts
  src/index.tsx
  yarn.lock
Labels: feat

#6 Feture/1 login
  .eslintrc.json
  package.json
  src/App.tsx
  src/components/auth/Login.tsx
  src/components/auth/LogoBox.tsx
  src/components/auth/TitleBox.tsx
  src/components/common/.gitkeep
  src/components/common/flexWrapper/index.tsx
  src/hooks/useForm.ts
  src/index.tsx
  src/pages/loginPage/index.tsx
  src/router.tsx
  src/styled.d.ts
  yarn.lock
Labels: feat, setting

#8 (#7) merge: toastProvider, container, toast 커스텀훅 추가
  package.json
  src/App.tsx
  src/hooks/useToast.tsx
  yarn.lock
Labels: feat

#11 (#10) merge: 학교 목록 불러오기 api, 파일 업로드 api 추가
  src/apis/files/index.ts
  src/apis/files/response.ts
  src/apis/schools/index.ts
  src/apis/schools/response.ts
Labels: feat

#13 (#12) merge: 로그인 리팩토링 및 로그인 로직 추가
  package.json
  src/App.tsx
  src/apis/auth/request.ts
  src/components/auth/Login.tsx
  src/hooks/useErrorMessage.tsx
  yarn.lock
Labels: feat, refactor

#14 (#3) merge: 비밀번호 재설정 작업
  package.json
  src/App.tsx
  src/apis/auth/index.ts
  src/components/auth/Certification.tsx
  src/components/auth/Login.tsx
  src/components/auth/LogoBox.tsx
  src/components/auth/Reset.tsx
  src/components/auth/TitleBox.tsx
  src/hooks/useDebounce.tsx
  src/hooks/useErrorMessage.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/ResetPasswordPage.tsx
  src/router.tsx
  src/styles/flexWrapper/index.tsx
  src/utils/regs.ts
  yarn.lock
Labels: feat

#18 (#17) merge: 2차 스프린트 api 정의
  src/apis/managers/index.ts
  src/apis/managers/response.ts
Labels: feat

#20 (#15) merge: 홈화면 퍼블리싱 및 기능 추가
  package.json
  src/apis/managers/index.ts
  src/apis/managers/response.ts
  src/components/main/DetailBox/PointBox.tsx
  src/components/main/DetailBox/StudentDetail.tsx
  src/components/main/DetailBox/StudentInfo.tsx
  src/components/main/Divider.tsx
  src/components/main/StudentBox.tsx
  src/components/main/StudentList.tsx
  src/pages/main.tsx
  src/router.tsx
  yarn.lock
Labels: feat

#24 (#23) merge: 애니메이션 추가 및 상세보기 닫히는 조건 수정
  package.json
  src/components/main/DetailBox/StudentDetail.tsx
  src/components/main/StudentBox.tsx
  src/components/main/StudentList.tsx
  src/pages/Main.tsx
  yarn.lock
Labels: feat
