Repository team-aliens/dms-front-admin, pull requests merged in 2023-03, with the labels that each got.

#68 (#67)merge: 학생 상세 확인 수정
  src/components/main/DetailBox/DetailBox.tsx
  src/components/main/DetailBox/PointBox.tsx
  src/components/main/DetailBox/StudentDetail.tsx
  src/components/main/DetailBox/StudentInfo.tsx
  src/components/main/StudentList.tsx
  src/components/modals/DeleteStudent.tsx
  src/hooks/useMangersApis.tsx
  src/pages/Home.tsx
Labels: feat

#85 상/벌점 항목 삭제 모달 에러 수정 및 모달 크기 조절
  src/apis/points/index.ts
  src/components/main/DetailBox/PointItem.tsx
  src/components/main/PointList.tsx
  src/components/main/StudentList.tsx
  src/components/modals/DeletePointOption.tsx
  src/components/modals/GivePointOptionsModal.tsx
  src/components/modals/ViewPointOptionsModal.tsx
  src/pages/Home.tsx
Labels: feat

#87 (#86)merge: 학교 확인 코드 재발급 재확인 모달
  src/components/modals/SchoolCheckingCode.tsx
  src/components/modals/ViewPointOptionsModal.tsx
  src/context/modal.tsx
  src/pages/myPage/index.tsx
Labels: feat

#89 (#88) merge: 자습실 신청 시간 설정 모달관련 리팩토링
  .yarn/install-state.gz
  src/apis/studyRooms/index.ts
  src/apis/studyRooms/response.ts
  src/components/apply/study/ListOptions.tsx
  src/components/modals/AddStudyRoomTime.tsx
  src/components/modals/LogOut.tsx
  src/components/modals/SetApplicationTime.tsx
  src/hooks/useAuthApi.tsx
  src/hooks/useMangersApis.tsx
  src/hooks/useNoticeApi.tsx
  src/hooks/usePointsApi.tsx
  src/hooks/useUsersApi.tsx
  src/pages/apply/study/StudyRoomList.tsx
Labels: feat, refactor

#93 (#92) merge: 상/벌점 필터 버그 및 상/벌점 부여 버그 수정
  src/apis/points/index.ts
  src/components/MultiRangeSlider.tsx
  src/components/modals/GivePointOptionsModal.tsx
  src/components/modals/ViewPointOptionsModal.tsx
Labels: 👾bug

#94 feat: 엑셀 파일 다운로드시 서버에서 보내주는 파일명 사용
  src/apis/points/index.ts
  src/apis/remains/index.tsx
  src/components/main/PointList.tsx
  src/components/modals/AddSeatType.tsx
  src/hooks/usePointsApi.tsx
  src/hooks/useRemainApi.tsx
  src/pages/Home.tsx
  src/pages/apply/remains/index.tsx
  src/utils/decoder.ts
  src/utils/excel.ts
Labels: feat, 👾bug

#97 (#96) merge: 기존에 일일이 관리하던 state를 useForm으로 관리하도록 수정
  src/apis/points/request.ts
  src/apis/points/response.ts
  src/components/main/DetailBox/PointItem.tsx
  src/components/modals/GivePointOptionsModal.tsx
  src/components/modals/ViewPointOptionsModal.tsx
Labels: feat, 👾bug

#101 feat: 토큰 재발급시에도 사용 가능한 기능 업데이트
  src/apis/auth/index.ts
  src/components/modals/LogOut.tsx
  src/hooks/useAuthApi.tsx
  src/pages/myPage/index.tsx
  src/utils/setUseableFeatures.ts
Labels: feat

#90 (#90) 잔류 페이지 버그 수정
  src/components/apply/remains/deleteModal.tsx
  src/components/apply/remains/remainModal.tsx
  src/components/apply/remains/timeModal.tsx
  src/context/modal.tsx
  src/pages/apply/index.tsx
  src/pages/apply/remains/index.tsx
  src/utils/translate.ts
Labels: 👾bug

#103 feat: 토스트 메세지가 부족한 부분 추가 및 모달 바깥부분 멈춰놓는 기능 추가
  .yarn/cache/@team-aliens-design-system-npm-1.4.5-54ee31f62c-8ebd3c6272.zip
  src/App.tsx
  src/apis/points/index.ts
  src/components/MultiRangeSlider.tsx
  src/components/main/DetailBox/DetailBox.tsx
  src/components/main/DetailBox/PointItem.tsx
  src/components/main/DetailBox/StudentDetailPoint.tsx
  src/components/main/StudentList.tsx
  src/components/modals/GivePointOptionsModal.tsx
  src/components/modals/LogOut.tsx
  src/components/modals/PointFilter.tsx
  src/components/modals/ViewPointOptionsModal.tsx
Labels: feat

#106 Fix : 잔류 페이지 수정
  src/apis/points/index.ts
  src/apis/points/request.ts
  src/apis/points/response.ts
  src/components/apply/remains/deleteModal.tsx
  src/components/apply/remains/remainModal.tsx
  src/components/apply/remains/timeModal.tsx
  src/components/modals/GivePointOptionsModal.tsx
  src/components/modals/LogOut.tsx
  src/components/modals/SchoolCheckingCode.tsx
  src/hooks/useRemainApi.tsx
  src/pages/apply/remains/index.tsx
Labels: refactor, 👾bug

#107 Fix : 레이아웃 오류 수정
  src/components/apply/remains/timeModal.tsx
Labels: 👾bug

#110 refactor: 필터 api 요청 방식 수정 및 학생 상/벌점 내역 요청 방식 수정
  src/apis/points/index.ts
  src/components/MultiRangeSlider.tsx
  src/components/main/DetailBox/StudentDetailPoint.tsx
  src/hooks/usePointsApi.tsx
Labels: performance

#108 (#98) merge: 토스트 에러 수정 및 상/벌점 부여시 선택 항목 해제
  src/apis/points/index.ts
  src/components/main/DetailBox/PointItem.tsx
  src/components/main/DetailBox/StudentDetailPoint.tsx
  src/components/main/PointList.tsx
  src/components/main/StudentList.tsx
  src/components/modals/GivePointOptionsModal.tsx
  src/components/modals/ViewPointOptionsModal.tsx
Labels: 👾bug

#114 feat: 404페이지
  src/App.tsx
  src/index.tsx
  src/pages/NotFound.tsx
  src/router.tsx
Labels: feat

#118 fix: service Cookie 여부 확인 후 로그아웃
  .pnp.cjs
  .pnp.loader.mjs
  .yarn/cache/@team-aliens-design-system-npm-1.4.6-2305efd770-206c677b98.zip
  .yarn/cache/@team-aliens-design-system-npm-1.4.9-5060d9643c-19deefe7ea.zip
  .yarn/releases/yarn-3.3.1.cjs
  package.json
  src/apis/schools/index.ts
  src/components/WithNavigatorBar.tsx
  src/hooks/useAuthApi.tsx
  src/hooks/useSchoolsApi.tsx
  src/pages/Home.tsx
  src/utils/queryKeys.ts
  src/utils/setUseableFeatures.ts
  yarn.lock
Labels: 👾bug

#123 feat: 상벌점 필터 위치 수정 및 태그 필터
  .pnp.cjs
  .pnp.loader.mjs
  .yarn/cache/@team-aliens-design-system-npm-1.4.11-d92b4e6579-48e4747726.zip
  .yarn/install-state.gz
  package.json
  src/App.tsx
  src/apis/managers/index.ts
  src/apis/managers/response.ts
  src/apis/remains/index.tsx
  src/apis/tags/index.ts
  src/apis/tags/request.ts
  src/apis/tags/response.ts
  src/components/main/DetailBox/DetailBox.tsx
  src/components/main/StudentBox.tsx
  src/components/main/StudentList.tsx
  src/components/main/Tag.tsx
  src/components/main/TagDropDown.tsx
  src/components/modals/DeleteStudentTag.tsx
  src/components/modals/GiveAllTagModal.tsx
  src/components/modals/ViewAllTagModal.tsx
  src/context/modal.tsx
  src/hooks/useMangersApis.tsx
  src/hooks/useTagApi.tsx
  src/hooks/useTagsApi.tsx
  src/pages/Home.tsx
  src/style/globalStyle.ts
  src/utils/atoms.ts
  src/utils/tagColor.ts
  yarn.lock
Labels: feat
